@startuml noindex
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Context.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml

Component(PageRenderService, "Page Render Service", "TypeScript Class")

System_Boundary(NoIndexCaldulation, "No Index Calculation") { 
    Component(IsNoIndex, "IsNoIndex", "TypeScript Class")

    Rel(PageRenderService, IsNoIndex, "Page, Response")
    Rel(IsNoIndex, PageRenderService, "IMetric<boolean>")
}

@enduml